<?php

/**
 * Implements hook_permission().
 */
function login_tools_permission() {
    return array(
        'administer login tools settings' => array(
          'title' => t('Administer settings for login tools'),
          'description' => t('Perform administration tasks for login tools.'),
        ),
      );    
}
/**
 * administration settings for login_tools
 * @return array             modified form
 */
function login_tools_admin() {
    $form = array();
    
    $form['login_tools_path'] = array(
        '#type' => 'textfield',
        '#title' => t('Path to login page'),
        '#default_value' => variable_get('login_tools_path', 'saml_login'),
        '#description' => t('Local path to the login page'),
        '#maxlength' => 256,
        );
    
    $form['login_tools_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Message to accompany login link'),
        '#default_value' => variable_get('login_tools_title', t('Cornell login required for access to form')),
        '#description' => t('Messsage to accompany login link'),
        '#maxlength' => 256,
        );
    
    return system_settings_form($form);
}

/**
 * Implements hook_menu().
 */
function login_tools_menu() {

    $items = array();
  
    $items['admin/settings/login_tools'] = array(
      'title' => 'Login tools module settings',
      'description' => 'Set up the login path',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('login_tools_admin'),
      'access arguments' => array('administer login tools settings'),
      'type' => MENU_CALLBACK,
     );
  
    return $items;
  }
  
/**
 * Implements hook_block_info().
 */
function login_tools_block_info() {
    // TODO Rename block deltas (e.g. delta-0) to readable strings.
    $blocks['login_tools']['info'] = t('Login Tools - require login to view a form');
    $blocks['login_tools']['cache'] = DRUPAL_NO_CACHE;
    return $blocks;
  }

/**
 * Implements hook_block_view().
 */
function login_tools_block_view($delta) {
    switch ($delta) {
        case 'login_tools':
            if (user_is_logged_in()) {
                $block['subject'] = '';
                $block['content'] = '';                    
            }
            else {
                $login_page = variable_get('login_tools_path', 'saml_login');
                $login = t('<a href="@url" title="@title">Login required</a>',
                    array('@url' => url($login_page, array('query' => drupal_get_destination())),
                        '@title' => t('Login, then return to this page')));
                $block['subject'] = variable_get('login_tools_title', t('Cornell login required for access to form'));
                $block['content'] = $login;
            }
            break;
    }
    return $block;       
}
